# coding: utf-8

"""
    Jupyter Server API

    Server API

    The version of the OpenAPI document: 5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.kernelspecs_api import KernelspecsApi


class TestKernelspecsApi(unittest.TestCase):
    """KernelspecsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KernelspecsApi()

    def tearDown(self) -> None:
        pass

    def test_api_kernelspecs_get(self) -> None:
        """Test case for api_kernelspecs_get

        Get kernel specs
        """
        pass


if __name__ == '__main__':
    unittest.main()
