# coding: utf-8

"""
    Jupyter Server API

    Server API

    The version of the OpenAPI document: 5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.terminals_api import TerminalsApi


class TestTerminalsApi(unittest.TestCase):
    """TerminalsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TerminalsApi()

    def tearDown(self) -> None:
        pass

    def test_api_terminals_get(self) -> None:
        """Test case for api_terminals_get

        Get available terminals
        """
        pass

    def test_api_terminals_post(self) -> None:
        """Test case for api_terminals_post

        Create a new terminal
        """
        pass

    def test_api_terminals_terminal_id_delete(self) -> None:
        """Test case for api_terminals_terminal_id_delete

        Delete a terminal session corresponding to an id.
        """
        pass

    def test_api_terminals_terminal_id_get(self) -> None:
        """Test case for api_terminals_terminal_id_get

        Get a terminal session corresponding to an id.
        """
        pass


if __name__ == '__main__':
    unittest.main()
