# coding: utf-8

"""
    Jupyter Server API

    Server API

    The version of the OpenAPI document: 5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nbserv_client.models.api_status import APIStatus

class TestAPIStatus(unittest.TestCase):
    """APIStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIStatus:
        """Test APIStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APIStatus`
        """
        model = APIStatus()
        if include_optional:
            return APIStatus(
                started = '',
                last_activity = '',
                connections = 1.337,
                kernels = 1.337
            )
        else:
            return APIStatus(
        )
        """

    def testAPIStatus(self):
        """Test APIStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
