# coding: utf-8

"""
    Jupyter Server API

    Server API

    The version of the OpenAPI document: 5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.api_spec_api import ApiSpecApi


class TestApiSpecApi(unittest.TestCase):
    """ApiSpecApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiSpecApi()

    def tearDown(self) -> None:
        pass

    def test_api_spec_yaml_get(self) -> None:
        """Test case for api_spec_yaml_get

        Get the current spec for the notebook server's APIs.
        """
        pass


if __name__ == '__main__':
    unittest.main()
