# coding: utf-8

"""
    Jupyter Server API

    Server API

    The version of the OpenAPI document: 5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.terminal import Terminal

class TestTerminal(unittest.TestCase):
    """Terminal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Terminal:
        """Test Terminal
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Terminal`
        """
        model = Terminal()
        if include_optional:
            return Terminal(
                name = '',
                last_activity = ''
            )
        else:
            return Terminal(
                name = '',
        )
        """

    def testTerminal(self):
        """Test Terminal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
