# coding: utf-8

"""
    Jupyter Server API

    Server API

    The version of the OpenAPI document: 5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nbserv_client.api.kernels_api import KernelsApi


class TestKernelsApi(unittest.TestCase):
    """KernelsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KernelsApi()

    def tearDown(self) -> None:
        pass

    def test_api_kernels_get(self) -> None:
        """Test case for api_kernels_get

        List the JSON data for all kernels that are currently running
        """
        pass

    def test_api_kernels_kernel_id_delete(self) -> None:
        """Test case for api_kernels_kernel_id_delete

        Kill a kernel and delete the kernel id
        """
        pass

    def test_api_kernels_kernel_id_get(self) -> None:
        """Test case for api_kernels_kernel_id_get

        Get kernel information
        """
        pass

    def test_api_kernels_kernel_id_interrupt_post(self) -> None:
        """Test case for api_kernels_kernel_id_interrupt_post

        Interrupt a kernel
        """
        pass

    def test_api_kernels_kernel_id_restart_post(self) -> None:
        """Test case for api_kernels_kernel_id_restart_post

        Restart a kernel
        """
        pass

    def test_api_kernels_post(self) -> None:
        """Test case for api_kernels_post

        Start a kernel and return the uuid
        """
        pass


if __name__ == '__main__':
    unittest.main()
