# coding: utf-8

"""
    Jupyter Server API

    Server API

    The version of the OpenAPI document: 5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nbserv_client.models.api_sessions_post501_response import ApiSessionsPost501Response

class TestApiSessionsPost501Response(unittest.TestCase):
    """ApiSessionsPost501Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiSessionsPost501Response:
        """Test ApiSessionsPost501Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiSessionsPost501Response`
        """
        model = ApiSessionsPost501Response()
        if include_optional:
            return ApiSessionsPost501Response(
                message = '',
                short_message = ''
            )
        else:
            return ApiSessionsPost501Response(
        )
        """

    def testApiSessionsPost501Response(self):
        """Test ApiSessionsPost501Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
