# coding: utf-8

"""
    Jupyter Server API

    Server API

    The version of the OpenAPI document: 5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.api_get200_response import ApiGet200Response

class TestApiGet200Response(unittest.TestCase):
    """ApiGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiGet200Response:
        """Test ApiGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiGet200Response`
        """
        model = ApiGet200Response()
        if include_optional:
            return ApiGet200Response(
                version = ''
            )
        else:
            return ApiGet200Response(
        )
        """

    def testApiGet200Response(self):
        """Test ApiGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
