# coding: utf-8

"""
    Jupyter Server API

    Server API

    The version of the OpenAPI document: 5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nbserv_client.api.config_api import ConfigApi


class TestConfigApi(unittest.TestCase):
    """ConfigApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConfigApi()

    def tearDown(self) -> None:
        pass

    def test_api_config_section_name_get(self) -> None:
        """Test case for api_config_section_name_get

        Get a configuration section by name
        """
        pass

    def test_api_config_section_name_patch(self) -> None:
        """Test case for api_config_section_name_patch

        Update a configuration section by name
        """
        pass


if __name__ == '__main__':
    unittest.main()
