# coding: utf-8

"""
    Jupyter Server API

    Server API

    The version of the OpenAPI document: 5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.contents import Contents

class TestContents(unittest.TestCase):
    """Contents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Contents:
        """Test Contents
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Contents`
        """
        model = Contents()
        if include_optional:
            return Contents(
                name = '',
                path = '',
                type = 'directory',
                writable = True,
                created = '',
                last_modified = '',
                size = 56,
                mimetype = '',
                content = '',
                format = '',
                hash = '',
                hash_algorithm = ''
            )
        else:
            return Contents(
                name = '',
                path = '',
                type = 'directory',
                writable = True,
                created = '',
                last_modified = '',
                mimetype = '',
                content = '',
                format = '',
        )
        """

    def testContents(self):
        """Test Contents"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
