# coding: utf-8

"""
    Jupyter Server API

    Server API

    The version of the OpenAPI document: 5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.kernel import Kernel

class TestKernel(unittest.TestCase):
    """Kernel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Kernel:
        """Test Kernel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Kernel`
        """
        model = Kernel()
        if include_optional:
            return Kernel(
                id = '',
                name = '',
                last_activity = '',
                connections = 1.337,
                execution_state = ''
            )
        else:
            return Kernel(
                id = '',
                name = '',
        )
        """

    def testKernel(self):
        """Test Kernel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
